version: "3"

services:
  processor_service:
    build: ./processor.service/
    command: go run ./cmd/main.go
    env_file:
      - .env
    depends_on:
      - kafka
    volumes: 
      - ./processor.service/:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1" #gateway do docker
  
  api:
    build: ./api/
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - kafka
    volumes: 
      - ./api/:/api/src
    extra_hosts:
     - "host.docker.internal:172.17.0.1" #gateway do docker
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1" #gateway do docker